In [69]:
import pandas as pd #pip install pandas
import numpy as np 
#pip install -U scikit-learn
import pickle
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [70]:
items = pd.read_csv('grocery.csv')
ratings = pd.read_csv('ratinggrocery.csv')
users = pd.read_csv('users.csv')

In [71]:
users.sample(10)

      User-ID  Age
1635    11235   29
361     23492   28
1601    22252   26
548     23305   25
936     22917   56
723     23130   14
1610    22243   25
610     23243   31
589     23264   34
277     23576   25

In [72]:
items.sample(10)

,ISBN,Grocery-Title,Book-Price,Image-URL-M,Image-URL-S,Image-URL-L
507,AA270,tapal danedar tea bags,Rs.485 per box,https://cdnprod.mafretailproxy.com/sys-master-...,http://images.amazon.com/images/P/042518630X.0...,NaN
611,AA156,maggi noodles.,Rs.45 per pcs,https://m.media-amazon.com/images/I/81dpDHc95A...,http://images.amazon.com/images/P/087113375X.0...,NaN
139,AA671,butter biscuit,Rs.150 per box,https://freshpicks.pk/wp-content/uploads/2020/...,http://images.amazon.com/images/P/0964778319.0...,NaN
189,AA617,shan biryani masala,Rs.90 per box,https://media.naheed.pk/catalog/product/cache/...,http://images.amazon.com/images/P/8445071408.0...,NaN
534,AA240,chicken.,Rs.550 per kg,https://www.healthbenefitstimes.com/9/uploads/...,http://images.amazon.com/images/P/0245542957.0...,NaN
546,AA227,.mitchells jam.,Rs.230 per jar,https://www.mitchells.com.pk/wp-content/upload...,http://images.amazon.com/images/P/8445071408.0...,NaN
558,AA214,.fresh milk,Rs.200 per ltr,https://encrypted-tbn0.gstatic.com/images?q=tb...,http://images.amazon.com/images/P/0679865691.0...,NaN
526,AA249,..tapal danedar,Rs.290 per pcs,https://cdn.shopify.com/s/files/1/0522/2357/41...,http://images.amazon.com/images/P/0425182908.0...,NaN
298,AA498,mospel,Rs.150 per pcs,https://media.naheed.pk/catalog/product/cache/...,http://images.amazon.com/images/P/0374157065.0...,NaN
336,AA456,fair and lovely women.,Rs.265 per pcs,https://cdn.shopify.com/s/files/1/0500/8723/16...,http://images.amazon.com/images/P/1569871213.0...,NaN

In [73]:
ratings.sample(10)

      User-ID   ISBN  Item-Rating
2778    11134  AA138            8
891     22960   BB35            8
2013    11204  AA563            2
1357    22494   BB20            3
1564    22287   BB13            8
406     23445   BB51            7
505     23346   BB48            5
80      43614   BB31            5
1707    11231  AA722            7
1177    22674   BB26            9

In [74]:
print(items.shape)
print(ratings.shape)
print(users.shape)

(754, 6)
(3038, 3)
(1760, 2)

In [75]:
items.isnull().sum()

ISBN               0
Grocery-Title      0
Book-Price         0
Image-URL-M        0
Image-URL-S       28
Image-URL-L      711
dtype: int64

In [76]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Item-Rating    0
dtype: int64

In [77]:
users.isnull().sum()

User-ID    0
Age        0
dtype: int64

In [78]:
items.duplicated().sum()

np.int64(0)

In [79]:
users.duplicated().sum()

np.int64(0)

In [80]:
ratings.duplicated().sum()

np.int64(0)

In [81]:
ratings_with_name = ratings.merge(items,on='ISBN')
ratings_with_name.sample(10)

,User-ID,ISBN,Item-Rating,Grocery-Title,Book-Price,Image-URL-M,Image-URL-S,Image-URL-L
1760,11227,AA707,5,bold body spray.,Rs.565 per pcs,https://cdn.shopify.com/s/files/1/0276/1110/33...,http://images.amazon.com/images/P/1569871213.0...,NaN
1130,22721,BB27,1,common sugar,Rs.200 per kg,http://cdn.shopify.com/s/files/1/0027/9222/692...,http://images.amazon.com/images/P/0812523873.0...,NaN
2984,11115,AA026,7,bay leaf,Rs.500 per kg,https://m.media-amazon.com/images/W/WEBP_40237...,http://images.amazon.com/images/P/0060938412.0...,http://images.amazon.com/images/P/0060938412.0...
636,23215,BB44,5,shan karahi msla,Rs.90 per box,https://media.naheed.pk/catalog/product/cache/...,http://images.amazon.com/images/P/0553062042.0...,NaN
1014,22837,BB31,2,nescafe coffee special,Rs.450 per pcs,http://cdn.shopify.com/s/files/1/0572/4779/332...,http://images.amazon.com/images/P/0060168013.0...,NaN
1777,11225,AA690,4,chocolate chip nuts,Rs.120 per box,https://pictures.grocerapps.com/original/groce...,http://images.amazon.com/images/P/1569871213.0...,NaN
418,23433,BB51,8,lux soap..,Rs.80 per pcs,https://media.naheed.pk/catalog/product/cache/...,http://images.amazon.com/images/P/055321215X.0...,NaN
2878,11125,AA090,9,tuvar daal,Rs.400 per kg,https://citydeal.s3.us-east-2.amazonaws.com/up...,http://images.amazon.com/images/P/0425182908.0...,NaN
1300,22551,BB21,1,corn flour special,Rs.220 per kg,https://homemadecuisine.biz/wp-content/uploads...,http://images.amazon.com/images/P/0446310786.0...,NaN
709,23142,BB41,5,oreo biscuits,Rs.200 per box,https://media.naheed.pk/catalog/product/cache/...,http://images.amazon.com/images/P/0553582747.0...,NaN

In [82]:
num_rating_df = ratings_with_name.groupby('Grocery-Title').count()['Item-Rating'].reset_index()
num_rating_df.rename(columns={'Item-Rating':'num_ratings'},inplace=True)
num_rating_df.sample(10)

                                 Grocery-Title  num_ratings
147                                 capri soap            2
545                               normal chana           30
444                                     mehran            2
455                            milcolu biscuit            2
62   alkarim dates ajwa premium airtight pack.            2
137                             butter biscuit            2
549                                        oil            2
446                        mehran chaat masala            2
659                             shaving creams            2
747                               youngs honey            2

In [83]:
print(ratings_with_name['Item-Rating'].dtype)
ratings_with_name['Item-Rating'] = pd.to_numeric(ratings_with_name['Item-Rating'], errors='coerce')
ratings_with_name = ratings_with_name.dropna(subset=['Item-Rating'])

int64

In [84]:
avg_rating_df = ratings_with_name.groupby('Grocery-Title')['Item-Rating'].mean().reset_index()
avg_rating_df.rename(columns={'Item-Rating': 'avg_rating'}, inplace=True)
print(avg_rating_df.sample(10))

                         Grocery-Title  avg_rating
272               fair and lovely mens    6.000000
443            meezan tea ultra rich..    5.000000
94                             biscuit    5.000000
269                      express power    7.000000
617                safeguard hand wash    4.500000
543  nivea men sensitive after shaving    8.000000
436                 meezan cooking oil    5.466667
325           gillete shaving fusion..    4.000000
170                            chicken    4.000000
173                           chicken.    3.000000

In [85]:
popular_df = num_rating_df.merge(avg_rating_df,on='Grocery-Title')
popular_df.sample(10)

             Grocery-Title  num_ratings  avg_rating
489                 mutton            2    7.000000
445  mehran biryani masala            2    1.500000
420                 maida.            2    5.500000
643        shan mix pickle            2    7.500000
621                 salt..            2    4.000000
618   safeguard hand wash.            2    7.500000
691            surf excel…           30    4.466667
719             tullo ghee            2    5.000000
269          express power            2    7.000000
184          click biscuit            2    4.500000

In [86]:
popular_df = popular_df[popular_df['num_ratings']>=30].sort_values('avg_rating',ascending=False).head(50)
popular_df.sample(10)

                Grocery-Title  num_ratings  avg_rating
350                  harpic..           37    5.000000
100       black pepper spices           30    5.333333
471                 moong dal           30    5.533333
1           mozzarella cheese           30    5.100000
436        meezan cooking oil           30    5.466667
188      coca cola cold drink           30    5.000000
697  tapal danedar tea strong           38    4.684211
190            cocomo biscuit           30    4.433333
523   nescafe  coffee special           41    4.560976
233                 desi eggs           30    6.200000

In [87]:
popular_df = popular_df.merge(items,on='Grocery-Title').drop_duplicates('Grocery-Title')[['Grocery-Title','Book-Price','Image-URL-M','num_ratings','avg_rating']]
popular_df.sample(10)

,Grocery-Title,Book-Price,Image-URL-M,num_ratings,avg_rating
20,black pepper spices,Rs.150 per kg,https://www.shutterstock.com/image-photo/close...,30,5.333333
33,shan karahi msla,Rs.90 per box,https://media.naheed.pk/catalog/product/cache/...,50,4.920000
45,oreo biscuits,Rs.200 per box,https://media.naheed.pk/catalog/product/cache/...,30,4.566667
47,surf excel…,Rs.255 per pcs,https://cdnprod.mafretailproxy.com/sys-master-...,30,4.466667
51,cherry blosom black,Rs.350 per pcs,https://media.naheed.pk/catalog/product/cache/...,30,4.333333
43,slice juice..,Rs.35 per pcs,https://cdnprod.mafretailproxy.com/sys-master-...,30,4.633333
32,mehran nihari msla,Rs.85 per pcs,https://mehrangroup.com/wp-content/uploads/202...,30,4.966667
16,moong dal,Rs.160 per kg,https://shanfoods.com/wp-content/uploads/2021/...,30,5.533333
9,gilete shaving G2,Rs.360 (3 pcs),https://static-01.daraz.pk/p/5b2727d0b4af4c779...,30,5.800000
7,normal chana,Rs.450 per kg,https://orbis.pk/wp-content/uploads/2017/04/05...,30,5.800000

In [88]:
x = ratings_with_name.groupby('User-ID').count()['Item-Rating'] > 2
regular_users = x[x].index
regular_users

Index([11111, 11112, 11113, 11114, 11115, 11116, 11117, 11118, 11119, 11120,
       ...
       11229, 11230, 11231, 11232, 11233, 11234, 11235, 11236, 11237, 11238],
      dtype='int64', name='User-ID', length=128)

In [89]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(regular_users)]
filtered_rating.sample(10)

,User-ID,ISBN,Item-Rating,Grocery-Title,Book-Price,Image-URL-M,Image-URL-S,Image-URL-L
2947,11119,AA057,8,deen's mozzarella cheese.,Rs.400 per pcs,https://media.naheed.pk/catalog/product/cache/...,http://images.amazon.com/images/P/1414035004.0...,NaN
2348,11173,AA377,6,kolson macroni fancy large elbow,Rs.200 per pcs,https://cdnprod.mafretailproxy.com/sys-master-...,http://images.amazon.com/images/P/067176537X.0...,NaN
2198,11187,AA465,5,mortein liquid.,Rs.230 per pcs,https://cdnprod.mafretailproxy.com/sys-master-...,http://images.amazon.com/images/P/0060973129.0...,NaN
2904,11123,AA082,5,salt..,Rs.90 per pcs,https://www.foodnavigator.com/var/wrbm_gb_food...,http://images.amazon.com/images/P/0966986105.0...,http://images.amazon.com/images/P/0966986105.0...
2450,11164,AA320,5,.brilla spaghetti,Rs.290 per pcs,https://thumbs.dreamstime.com/b/tyumen-russia-...,http://images.amazon.com/images/P/0425182908.0...,NaN
1813,11222,AA669,2,cocunut biscuit,Rs.240 per box,https://www.continentalbiscuits.com.pk/product...,http://images.amazon.com/images/P/0553280333.0...,NaN
2536,11156,AA270,4,tapal danedar tea bags,Rs.485 per box,https://cdnprod.mafretailproxy.com/sys-master-...,http://images.amazon.com/images/P/042518630X.0...,NaN
2033,11202,AA549,4,dove shampoo.,Rs.500 per pcs,https://www.dove.com/content/dam/unilever/dove...,http://images.amazon.com/images/P/0060914068.0...,NaN
2960,11118,AA047,7,meezan ghee.,Rs.550 per pcs,https://mezangrp.com/wp-content/uploads/2019/0...,http://images.amazon.com/images/P/0439095026.0...,NaN
2595,11151,AA250,8,olpers cream.,Rs.200 per pcs,https://esajee.com/media/catalog/product/cache...,http://images.amazon.com/images/P/1567407781.0...,NaN

In [90]:
y = filtered_rating.groupby('Grocery-Title').count()['Item-Rating']>=1
famous_items = y[y].index
famous_items

Index([' chaat masala', '..adams butter', '..blue band butter',
       '..bradys rusk', '..brilla spaghetti', '..chakki flour', '..chicken',
       '..dettol hand sanitizer', '..eva oil', '..face wash',
       ...
       'white sugar', 'white sugar.', 'white sugar..', 'wipes', 'yogurt',
       'young's mayo garlic mayonnaise', 'young's mayo garlic mayonnaise.',
       'young's mayonnaise', 'youngs honey', 'zeera plus'],
      dtype='object', name='Grocery-Title', length=701)

In [91]:
final_ratings = filtered_rating[filtered_rating['Grocery-Title'].isin(famous_items)]
final_ratings.sample(10)

,User-ID,ISBN,Item-Rating,Grocery-Title,Book-Price,Image-URL-M,Image-URL-S,Image-URL-L
2927,11121,AA071,8,brown rice,Rs.100 per kg,https://images.unsplash.com/photo-161372891334...,http://images.amazon.com/images/P/0380715899.0...,NaN
2765,11135,AA148,8,dairy life cheese,Rs.350 per pcs,https://cdn.metro-online.pk/dashboard/prod-pic...,http://images.amazon.com/images/P/0060938412.0...,NaN
1875,11216,AA629,1,mehran biryani masala,Rs.85 per pcs,https://mehrangroup.com/wp-content/uploads/202...,http://images.amazon.com/images/P/0671870432.0...,NaN
2881,11125,AA093,7,tota rice.,Rs.170 per kg,http://cdn.shopify.com/s/files/1/0572/4779/332...,http://images.amazon.com/images/P/3442353866.0...,NaN
2456,11163,AA315,8,shangrila tomato ketchup,Rs.245 per pcs,https://i0.wp.com/fairo.pk/wp-content/uploads/...,http://images.amazon.com/images/P/0375509038.0...,NaN
2235,11183,AA434,1,dish washer,###,https://www.ikea.com/in/en/images/products/ski...,http://images.amazon.com/images/P/0312970242.0...,NaN
2208,11186,AA452,5,frey room spray.,Rs.1250 per pcs,https://cdn.shopify.com/s/files/1/0081/3504/92...,http://images.amazon.com/images/P/0553062042.0...,NaN
2292,11178,AA400,1,alkarim dates ajwa premium airtight pack,Rs.900 per box,https://esajee.com/media/catalog/product/cache...,http://images.amazon.com/images/P/0842342702.0...,NaN
1724,11230,AA716,4,eos shea butter shaving cream,Rs.2750 per pcs,https://m.media-amazon.com/images/I/310Xtwcr4X...,http://images.amazon.com/images/P/080652121X.0...,NaN
2065,11199,AA536,7,just juice,Rs.80 per pcs,https://i.pinimg.com/originals/28/ec/e8/28ece8...,http://images.amazon.com/images/P/055321215X.0...,NaN

In [92]:
pt = final_ratings.pivot_table(index='Grocery-Title',columns='User-ID',values='Item-Rating')
pt.sample(10)

User-ID,11111,11112,11113,11114,11115,11116,11117,11118,11119,11120,...,11229,11230,11231,11232,11233,11234,11235,11236,11237,11238
Grocery-Title,,,,,,,,,,,,,,,,,,,,,
national soya sauce.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max all purpose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
passion perfume.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
marinda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
..chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gillete shaving gel refreshing breeze,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,7.0,5.0,NaN,NaN,NaN,NaN
real juice,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nestle nido school age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
chakki flour.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
nescafe cold coffee..,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [93]:
pt.fillna(0,inplace=True)

In [94]:
pt.sample(20)

User-ID,11111,11112,11113,11114,11115,11116,11117,11118,11119,11120,...,11229,11230,11231,11232,11233,11234,11235,11236,11237,11238
Grocery-Title,,,,,,,,,,,,,,,,,,,,,
capri soap..,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,5.0
power plus shoe shiner.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
white sugar..,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
national garlic mayonnaise,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sugar,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
.freesh milk,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
tuc biscuit.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
pine nuts,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
oral b,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,5.0
apple,5.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
.habib oil,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
..eva oil,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
snickers,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
omung dobala cream,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
nivea cream,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dalda ghee,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,6.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
beef,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
black cumin,0.0,0.0,0.0,0.0,4.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
bright shine air freshner.,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
tapal danedar..,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [95]:
from sklearn.metrics.pairwise import cosine_similarity

In [96]:
similarity_scores = cosine_similarity(pt)
similarity_scores

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(701, 701))

In [97]:
similarity_scores.shape

(701, 701)

In [98]:
def recommend(product_name):
    # index fetch
    index = np.where(pt.index==product_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_scores[index])),key=lambda x:x[1],reverse=True)[0:14]
    
    data = []
    for i in similar_items:
        item = []
        temp_df = items[items['Grocery-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Grocery-Title')['Grocery-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Grocery-Title')['Book-Price'].values))
        item.extend(list(temp_df.drop_duplicates('Grocery-Title')['Image-URL-M'].values))
        
        data.append(item)
    
    return data

In [99]:
recommend('dew')

[['dew',
  'Rs.160 per pcs',
  'https://cdnprod.mafretailproxy.com/sys-master-root/h59/h43/26911827853342/46349_main.jpg_480Wx480H'],
 ['sprite',
  'Rs.160 per pcs',
  'https://www.arysahulatbazar.pk/content/images/thumbs/0076389_coke-sprite-soft-drink-pet-bottle_450.jpeg'],
 ['marinda ',
  'Rs.160 per pcs',
  'https://pictures.grocerapps.com/original/grocerapp-marinda-5fbf41dcede2a.jpeg'],
 ['pepsi ',
  'Rs.160 per pcs',
  'https://cdnprod.mafretailproxy.com/sys-master-root/h46/hdb/26911820939294/46319_main.jpg_480Wx480H'],
 ['just juice.',
  'Rs.80 per pcs',
  'https://i.pinimg.com/originals/28/ec/e8/28ece8df37dbf2d0c690f3d8f05777c7.jpg'],
 ['coca cola',
  'Rs.160 per pcs',
  'https://rashanwalaa.pk/wp-content/uploads/2022/03/Coke-Soft-Drink-2.25ltr.png'],
 ['cold drinks',
  '###',
  'https://cdn.shopify.com/s/files/1/0436/7371/4851/products/colddrink.jpg?v=1638350070'],
 ['real juice.',
  'Rs.160 per pcs',
  'https://5.imimg.com/data5/FW/XJ/VA/SELLER-30759087/real-mixed-fruit-juice-500x500.jpg'],
 ['sprite sugar free',
  'Rs.140 per pcs',
  'https://assets.woolworths.com.au/images/2010/271637.jpg?impolicy=wowcdxwbjbx&w=900&h=900'],
 ['mango juice.',
  'Rs.35 per pcs',
  'http://cdn.shopify.com/s/files/1/0522/2357/4165/products/5078643001017_grande.jpg?v=1629875655'],
 ['sting red',
  'Rs.75 per pcs',
  'https://blackandbrownbakers.com/wp-content/uploads/2021/04/Sting-Red-500-ML.jpg'],
 [' chaat masala',
  'Rs.90 per box',
  'https://media.naheed.pk/catalog/product/cache/49dcd5d85f0fa4d590e132d0368d8132/a/-/a-1_4_4.jpg'],
 ['..adams butter',
  'Rs.250 per pcs',
  'https://media.naheed.pk/catalog/product/cache/49dcd5d85f0fa4d590e132d0368d8132/1/0/1078925-1.jpg'],
 ['..blue band butter',
  'Rs.190 per pcs',
  'https://media.naheed.pk/catalog/product/cache/49dcd5d85f0fa4d590e132d0368d8132/a/-/a-1_4.jpg']]

In [100]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))

In [101]:
items.drop_duplicates('Grocery-Title')

,ISBN,Grocery-Title,Book-Price,Image-URL-M,Image-URL-S,Image-URL-L
0,BB60,national tomato ketchup litre,Rs.90 per pcs,https://pictures.grocerapps.com/original/groce...,http://images.amazon.com/images/P/8445071408.0...,NaN
1,BB59,kolson macroni packet,Rs.150 per pcs,https://media.naheed.pk/catalog/product/cache/...,http://images.amazon.com/images/P/055321215X.0...,NaN
2,BB58,fresh honey special,Rs.500 per kg,https://i0.wp.com/post.healthline.com/wp-conte...,http://images.amazon.com/images/P/0380715899.0...,NaN
3,BB57,surf excel…,Rs.255 per pcs,https://cdnprod.mafretailproxy.com/sys-master-...,http://images.amazon.com/images/P/0394743741.0...,NaN
4,BB56,fog body spray….,Rs.755 per pcs,https://cdn2.bigcommerce.com/n-biq04i/ivmp9iza...,http://images.amazon.com/images/P/087113375X.0...,NaN
...,...,...,...,...,...,...
749,AA005,strawberry,Rs.220 per box,https://m.media-amazon.com/images/W/WEBP_40237...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
750,AA004,banana,Rs.200 per dozen,https://m.media-amazon.com/images/W/WEBP_40237...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
751,AA003,apple,Rs.240 per kg,https://m.media-amazon.com/images/W/WEBP_40237...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
752,AA002,mango,Rs.180 per kg,https://m.media-amazon.com/images/W/WEBP_40237...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
753,AA001,fruit,###,https://hips.hearstapps.com/hmg-prod.s3.amazon...,NaN,NaN

In [102]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(items,open('books.pkl','wb'))
pickle.dump(similarity_scores,open('similarity_scores.pkl','wb'))